name: voltage_treasure_hunt
description: A treasure hunt application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0

  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  just_audio: ^0.9.35
  location: ^5.0.0
  lottie: ^2.6.0
  provider: ^6.0.5
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/keys.env
    - assets/animations/
    - assets/images/
    - assets/audio/
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-VariableFont_wght.ttf

    - family: MooLahLah
      fonts:
        - asset: assets/fonts/MooLahLah-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
